name: ministock
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  fl_chart: ^0.36.1
  qr_code_scanner: ^0.4.0   		# สแกน
  qr_flutter: ^3.2.0 			      # แสดงผล
  qr_code_tools: ^0.0.6 		    # จัดการเช่นแปะรูปลงบน qrcode
  image_picker_saver: ^0.3.0		# เปิดกล้อง และ gallery
  path_provider: ^2.0.1			    # อ่านที่อยู่ของภาพ
  path: ^1.8.0			            # กำหนดที่อยู่ของภาพ
  rxdart: ^0.22.5			          # ตัวแปลง dart ให้อยู่ในรูปแบบ reactive dart
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/

  fonts:
    - family: NotoSansThaiUI
      fonts:
        - asset: fonts/NotoSansThaiUI-Regular.ttf
        - asset: fonts/NotoSansThaiUI-Thin.ttf
        - asset: fonts/NotoSansThaiUI-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
